# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250316-220216-happy-darter

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
    intent_tokenization_flag: False
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true
    use_word_boundaries: false
    case_sensitive: false
  - name: CountVectorsFeaturizer
    case_sensitive: False
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 200
    evaluate_every_number_of_epochs: 10
    model_confidence: softmax
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
  - name: FallbackClassifier
    threshold: 0.01

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.0
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: False
  - name: MemoizationPolicy
  - name: TEDPolicy